name: omeropy-ilastik
channels:
  - ome
  - conda-forge
  - defaults
  - ilastik-forge
dependencies:
  - python=3.7
  - pandas
  - matplotlib
  - scipy
  - numpy
  - pillow
  - scikit-image
  - scikit-learn
  - h5py<3.2
  - skan
  - ipywidgets
  - tornado<6
  - ilastik-dependencies-no-solvers==1.4.3
  - ilastik-forge/label/ilastik140::ilastik-meta==1.4.0b14  # ilastik-forge
  - pip
  # ome: minimal dependencies required to use the Python API
  - omero-py
  - pip:
    - ome-zarr
    - dask-image
    - stardist
    - tensorflow
    - yapsy
    - itkwidgets
