name: omeropy-ilastik
channels:
  - ome
  - ilastik-forge/label/ilastik140
  - ilastik-forge
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.2
  - argcomplete=1.12.3
  - argon2-cffi=21.1.0
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.0
  - bioimageio.spec=0.3.3.post6
  - bleach=4.1.0
  - blosc=1.21.0
  - boost=1.72.0
  - boost-cpp=1.72.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charls=2.2.0
  - click=8.0.3
  - cloudpickle=2.0.0
  - coincbc=2.10.5
  - colorama=0.4.4
  - cryptography=35.0.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - dpct=1.2.post36
  - elf=0.2.1.post7
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.4.1
  - fastfilters=0.2.6.post20
  - fftw=3.3.10
  - freetype=2.10.4
  - fs=2.4.11
  - fsspec=2021.10.1
  - future=0.18.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.0
  - glib-tools=2.70.0
  - glpk=4.65
  - gmp=6.2.1
  - greenlet=1.1.2
  - grpcio-tools=1.33.2
  - h5py=2.10.0
  - hdf5=1.10.6
  - hytra=1.1.4.post66
  - icu=68.2
  - idna=2.10
  - ilastik-dependencies-no-solvers=1.4.3
  - ilastik-feature-selection=0.123.post31
  - ilastik-meta=1.4.0b14
  - ilastikrag=0.1.3.post40
  - ilastiktools=0.2.post32
  - ilmbase=2.5.5
  - imagecodecs=2021.2.26
  - imageio=2.9.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - ipykernel=6.4.2
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - jsonschema=4.1.2
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - jxrlib=1.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lemon=1.3.1
  - lerc=2.2.1
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.79.1
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.18.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - llvm-openmp=12.0.1
  - llvmlite=0.36.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - mamutexport=0.2.1.post5
  - marching_cubes=0.3.post5
  - markupsafe=2.0.1
  - marshmallow=3.14.0
  - marshmallow-jsonschema=0.13.0
  - marshmallow-union=0.1.15.post1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - more-itertools=8.10.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - ndstructs=0.0.5dev0
  - nest-asyncio=1.5.1
  - networkx=2.5
  - nifty=v1.0.7
  - nose=1.3.7
  - notebook=6.1.6
  - nspr=4.32
  - nss=3.71
  - numba=0.53.0
  - numpy-allocation-tracking=0.2.post11
  - olefile=0.46
  - omero-py=5.10.0
  - openexr=2.5.5
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=0.24.2
  - pandoc=2.15
  - pandocfilters=1.5.0
  - paramiko=2.8.0
  - parso=0.8.2
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickle5=0.0.11
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=21.3.1
  - pluggy=1.0.0
  - pooch=1.5.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.21
  - protobuf=3.18.1
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - pycparser=2.20
  - pygments=2.10.0
  - pynacl=1.4.0
  - pyopengl=3.1.5
  - pyopenssl=21.0.0
  - pyparsing=3.0.3
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtgraph=0.12.3
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=3.10.1
  - pytest-qt=4.0.2
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-stdnum=1.17
  - python_abi=3.7
  - pytiff=0.8.1
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qimage2ndarray=1.8.3
  - qt=5.12.9
  - readline=8.1
  - requests=2.25.1
  - ruamel.yaml=0.17.16
  - ruamel.yaml.clib=0.2.2
  - scikit-image=0.18.1
  - scikit-learn=0.20.3
  - scipy=1.6.1
  - send2trash=1.8.0
  - setuptools=58.2.0
  - shellingham=1.4.0
  - skan=0.9
  - snappy=1.1.8
  - sqlite=3.36.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tifffile=2021.3.17
  - tiktorch-client=21.7.0
  - tk=8.6.11
  - toolz=0.11.1
  - tornado=5.1.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typer=0.4.0
  - urllib3=1.26.7
  - vigra=1.11.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.2
  - wsdt=0.2.post25
  - xarray=0.14.1
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - yapsy=1.12.2
  - z5py=2.0.5
  - zeroc-ice36-python=3.6.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.15.0
    - aiobotocore==1.4.2
    - aiohttp==3.7.4.post0
    - aioitertools==0.8.0
    - asciitree==0.3.3
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - botocore==1.20.106
    - colorcet==2.0.6
    - csbdeep==0.6.3
    - dask-image==0.6.0
    - fasteners==0.16.3
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==2.3.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - ipydatawidgets==4.2.0
    - ipympl==0.8.2
    - itk-core==5.2.1.post1
    - itk-filtering==5.2.1.post1
    - itk-meshtopolydata==0.7.1
    - itk-numerics==5.2.1.post1
    - itkwidgets==0.32.1
    - jmespath==0.10.0
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - multidict==5.2.0
    - numcodecs==0.9.1
    - numpy==1.19.5
    - oauthlib==3.1.1
    - ome-zarr==0.2.0
    - opt-einsum==3.3.0
    - param==1.12.0
    - pims==0.5
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyct==0.4.8
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - s3fs==2021.10.1
    - six==1.15.0
    - slicerator==1.0.0
    - stardist==0.7.3
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.3
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - traittypes==0.2.1
    - typing-extensions==3.7.4.3
    - werkzeug==2.0.2
    - wrapt==1.12.1
    - yarl==1.7.0
    - zarr==2.10.2
    - zstandard==0.16.0
